repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: forbid-crlf # Forbid files containing CRLF end-lines to be committed
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        language: golang
        types: [yaml]
        files: ^\.github/workflows/
        entry: actionlint
        minimum_pre_commit_version: 3.0.0
  - repo: local
    hooks:
      - id: make_lint
        name: Run StyLua
        language: system
        entry: "make lint"
        files: (lua|test)/.*lua$
        verbose: true
      - id: make_check
        name: Run Selene
        language: system
        entry: "make check"
        files: lua/.*lua$
        verbose: true
      - id: make_clean
        name: Clean help tags
        language: system
        entry: "make clean"
        files: doc/.*\.txt$
        verbose: true
      - id: make_docs
        name: Generate local help tags
        language: system
        entry: make
        files: doc/.*\.txt$
        verbose: true
