name: LuaRocks Release
on:
  pull_request: # Will test a local install without uploading to luarocks.org
  workflow_dispatch:
jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7.2.0
        with:
          version: "0.4.1"
          license: "Apache-2.0"
          detailed_description: |
            A Neovim plugin written in Lua that, under configurable conditions, automatically sets
            the user's cwd to the current project root and provides project management.
          labels: |
            neovim
          copy_directories: |
            {{ neovim.plugin.dirs }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
