name: Action Release
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  merge_group:
    branches:
      - main
  release:
    types:
      - created
jobs:
  release:
    name: Make Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Project Assets
        run: |
          mkdir -pv project.nvim
          cp -rv lua doc README.md CREDITS.md LICENSE Makefile project.nvim
          zip -r -9 project.nvim.zip project.nvim
          tar cvJf project.nvim.tar.xz project.nvim
          tar cvzf project.nvim.tar.gz project.nvim
          sha512sum project.nvim.zip project.nvim.tar.xz project.nvim.tar.gz >| sha512sums.txt
          md5sum project.nvim.zip project.nvim.tar.xz project.nvim.tar.gz >| md5sums.txt
          rm -rfv project.nvim
      - name: Get Release
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true
          prerelease: true
          pattern: '^v.*'
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2.5.0
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            project.nvim.tar.gz
            project.nvim.tar.xz
            project.nvim.zip
            md5sums.txt
            sha512sums.txt
          token: ${{ secrets.GITHUB_TOKEN }}
  luarocks-release:
    needs: release
    runs-on: ubuntu-latest
    name: LuaRocks Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7.2.0
        with:
          version: "0.2.1"
          license: "Apache-2.0"
          detailed_description: |
            A Neovim plugin written in Lua that, under configurable conditions, automatically sets
            the user's cwd to the current project root and provides project management.
          labels: |
            neovim
          copy_directories: |
            {{ neovim.plugin.dirs }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
